# Travis CI configuration file for running tests
language: python
dist: xenial
python:
  - "2.7"
  - "3.6"

branches:
  only:
  - master

services:
  - docker

addons:
  apt:
    packages:
      - nodejs

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install -o Dpkg::Options::="--force-confold" docker-ce

install:
  - "pip install demjson"
  - "pip install -r requirements.txt"
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then pip install -r requirements3.txt; fi

env:
  - MAKE_TARGET=test.syntax SHARD=0 SHARDS=1
  - MAKE_TARGET=test.playbooks SHARD=0 SHARDS=1
  - MAKE_TARGET=docker.test.shard SHARD=0 SHARDS=4
  - MAKE_TARGET=docker.test.shard SHARD=1 SHARDS=4
  - MAKE_TARGET=docker.test.shard SHARD=2 SHARDS=4
  - MAKE_TARGET=docker.test.shard SHARD=3 SHARDS=4

script:
  - docker --version
  - make --version
  - travis_wait 90 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS
