#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Deploy completion aggregator update cron job
#
# See documentation in README.rst

#
# This file contains the variables you'll need to pass to the role, and some
# example values.

update_completion_aggregator_script: "/edx/var/update_completion_aggregator.sh"
COMPLETION_AGGREGATOR_ENABLE_CRON_JOB: false
update_completion_cron_job_hours: "*"
update_completion_cron_job_minutes: 0
