# Bootstrap packages must be installed with raw commands, because ubuntu
# xenial+ cloud images don't have python2.7 installed, and ansible doesn't yet
# support python3.

- name: Update apt-get
  become: true
  raw: apt-get update
  register: python_update_result
  retries: 10
  delay: 10

- debug:
    var: python_update_result

- name: Install packages
  raw: "apt-get install {{ item }}"
  with_items: "{{ python_packages }}"
  register: apt_install

- debug:
    var: apt_install
