# Bootstrap packages must be installed with raw commands, because ubuntu
# xenial+ cloud images don't have python2.7 installed, and ansible doesn't yet
# support python3.

- name: Print repos
  become: true
  raw: cat /etc/apt/sources.list | grep -v -e '#' -e '^$'
  register: repos_output

- name: Debug repos
  debug:
    var: repos_output

- name: Update apt-get
  become: true
  raw: apt-get update
  register: python_update_result
  retries: 10
  delay: 10

- debug:
    var: python_update_result

- name: Search for python-minimal
  become: true
  raw: apt-cache search python-minimal
  register: search_result

- name: Debug search for python-minimal
  debug:
    var: search_result

- name: Install packages
  raw: "apt-get install -y {{ item }}"
  with_items: "{{ python_packages }}"
  register: apt_install

- debug:
    var: apt_install
