---
- name: Create Apple Pay certificates directory
  file:
    path: "{{ ecommerce_apple_pay_merchant_certificate_directory }}"
    state: directory
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: Write Apple Pay merchant certificates
  copy:
    content: "{{ ECOMMERCE_APPLE_PAY_MERCHANT_CERTIFICATE }}"
    dest: "{{ ecommerce_apple_pay_merchant_certificate_path }}"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  no_log: true
  tags:
    - install
    - install:configuration

# Install any custom extra requirements if defined in ECOMMERCE_EXTRA_REQUIREMENTS.
- name: install python extra requirements
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    extra_args: "--exists-action w {{ item.extra_args|default('') }}"
    virtualenv: "{{ ecommerce_venv_dir }}"
    state: present
  with_items: "{{ ECOMMERCE_EXTRA_REQUIREMENTS }}"
  become_user: "{{ ecommerce_user }}"
  tags:
    - install
    - install:app-requirements
