---

temp_repo_dir: "{{ edxapp_code_dir }}/.temp_repo"

tinymce_dir: "{{ edxapp_code_dir }}/common/static/js/vendor/tinymce"
tinymce_plugins_dir: "{{ tinymce_dir }}/js/tinymce/plugins"

edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"
