---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role openstack
#

OPENSTACK_ENABLE_SWIFT_LOG_SYNC: false

# Credentials for log sync script
SWIFT_LOG_SYNC_USERNAME: ''
SWIFT_LOG_SYNC_PASSWORD: ''
SWIFT_LOG_SYNC_TENANT_ID: ''
SWIFT_LOG_SYNC_TENANT_NAME: ''
SWIFT_LOG_SYNC_AUTH_URL: ''
SWIFT_LOG_SYNC_REGION_NAME: ''

openstack_role_name: openstack

openstack_dirs:
  home:
    path: "{{ COMMON_APP_DIR }}/{{ openstack_role_name }}"
    owner: "root"
    group: "root"
    mode: "0755"
  logs:
    path: "{{ COMMON_LOG_DIR }}/{{ openstack_role_name }}"
    owner: "syslog"
    group: "syslog"
    mode: "0650"

openstack_requirements_file: "{{ edxapp_code_dir }}/requirements/edx/openstack.txt"

openstack_log_sync_script: "{{ openstack_dirs.home.path }}/send-logs-to-swift"
openstack_log_sync_script_environment: "{{ openstack_dirs.home.path }}/log-sync-env.sh"
openstack_swift_logfile: "{{ openstack_dirs.logs.path }}/log-sync.log"

openstack_swift_log_sync: "{{ COMMON_OBJECT_STORE_LOG_SYNC and OPENSTACK_ENABLE_SWIFT_LOG_SYNC }}"

openstack_debian_pkgs:
  - python-setuptools

openstack_pip_pkgs:
  - python-keystoneclient
  - python-swiftclient
