---
dependencies:
  - common
  - supervisor
  - role: automated
    AUTOMATED_USERS: "{{ edx_django_service_automated_users }}"
  - role: edx_service
    edx_service_name: "{{ edx_django_service_name }}"
    edx_service_config: "{{ edx_django_service_config }}"
    edx_service_repos: "{{ edx_django_service_repos }}"
    edx_service_user: "{{ edx_django_service_user }}"
    edx_service_home: "{{ edx_django_service_home }}"
    edx_service_packages:
      debian: "{{ edx_django_service_debian_pkgs }}"
      redhat: []
    edx_service_decrypt_config_enabled: "{{ edx_django_service_decrypt_config_enabled }}"
    edx_service_copy_config_enabled: "{{ edx_django_service_copy_config_enabled }}"
