---

- name: Minify tinymce plugin files
  block:
    - name: Unarchive JakePackage.zip
      unarchive:
        src: "{{ edx_jake_package }}"
        dest: "{{ tinymce_dir }}"
        remote_src: True
    - name: Clean existing node modules
      file:
        state: absent
        path: "{{ tinymce_dir }}/node_modules"
    - name: Install npm dependencies from archive
      shell: "npm install"
      args:
        chdir: "{{ tinymce_dir }}"
    - name: Clean existing tinymce js files with jake
      shell: "npx jake clean-js"
      args:
        chdir: "{{ tinymce_dir }}"
    - name: Build tinymce with jake
      shell: "npx jake minify bundle[themes:*,plugins:*]"
      args:
        chdir: "{{ tinymce_dir }}"
  become_user: "{{ edxapp_user }}"

# There are problems with django collectstatic copying files.  It doesn't retain
# last modified timestamps, but relies on those same timestamps to know if a new file
# should be recopied.  While collectstatic --clear exists, it only clears some of the
# files in edxapp_staticfile_dir, it leaves postprocessed or otherwise hashed files.
# This ensures we have a totally clean directory.
- name: Remove and recreate the staticfiles directory so nothing stale can exist
  file:
      path: "{{ edxapp_staticfile_dir }}"
      state: "{{ item }}"
      owner: "{{ edxapp_user }}"
      group: "{{ common_web_group }}"
      mode:  "0755"
  when: celery_worker is not defined and not devstack
  with_items: ['absent', 'directory']
  tags:
    - gather_static_assets
    - assets

# Gather assets using paver if possible
- name: "gather static assets with paver"
  command: "{{ COMMON_BIN_DIR }}/edxapp-update-assets"
  when: celery_worker is not defined and not devstack
  tags:
    - gather_static_assets
    - assets

- name: Restart LMS
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "lms"

- name: Restart CMS
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "cms"
