---

tinymce_adsk_plugin_repo: "https://gitlab.com/nizarmah/tinymce-adsk-plugin"
tinymce_adsk_plugin_branch: "master"
tinymce_adsk_plugin_dir_name: "adsklink"
tinymce_adsk_plugin_temp_dir: "{{ edxapp_code_dir }}/.temp_tinymce_adsk_plugin"

tinymce_dir: "{{ edxapp_code_dir }}/common/static/js/vendor/tinymce"
tinymce_plugins_dir: "{{ tinymce_dir }}/js/tinymce/plugins"

edx_jake_package: "{{ edxapp_code_dir }}/vendor_extra/tinymce/JakePackage.zip"

tinymce_themes:
  - modern

tinymce_plugins:
  - "{{ tinymce_adsk_plugin_dir_name }}"
  - advlist
  - anchor
  - autolink
  - charmap
  - code
  - codemirror
  - contextmenu
  - image
  - insertdatetime
  - link
  - lists
  - media
  - paste
  - print
  - save
  - searchreplace
  - table
  - textcolor
  - visualblocks
