---
dependencies:
  - common
  - supervisor
  - role: edx_service_with_rendered_config
    edx_service_with_rendered_config_service_name: "{{ xqueue_service_name }}"
    edx_service_with_rendered_config_service_config: "{{ XQUEUE_CONFIG }}"
    edx_service_with_rendered_config_filter_nones: true
    edx_service_with_rendered_config_repos: "{{ XQUEUE_REPOS }}"
    edx_service_with_rendered_config_user: "{{ xqueue_user }}"
    edx_service_with_rendered_config_home: "{{ xqueue_home }}"
    edx_service_with_rendered_config_packages:
      debian: "{{ xqueue_debian_pkgs }}"
      redhat: []
